server:
  port: 8080
eureka:
  client:
    service-url:
      # 设置与Eureka Server的地址,查询服务和注册服务都需要依赖这个地址.默认是http://localhost:8761/eureka/;多个地址可使用','风格.
      defaultZone: http://localhost:8888/eureka/
spring:
  application:
    name: test-cli
